### ISSUE TITLE
Original data NOT available?

### ISSUE THREAD

**Issue by TREE985** [ssarfraz/QuoVadisTAD#7]
Just find the dataset not in the DATA_DIR. And I can't get the F1 score 0.833 for SWaT when I use the data provided in README(actually just got 0.546). Can anyone provide the original data for reproduce？ Thanks a lot if anyone can help

**Comment by ssarfraz** [comment]
hi, please request a data access for WADI and SwAT from iTrust.  you can then prepare it using scripts which we followed from [here](https://github.com/d-ailin/GDN/tree/main/scripts), or else once you have the permissions  and can send a copy of the approval via email to me,  I can provide you the prepared data files which you can readily use.
